spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meta_test?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    sunbeam.base.metadata.mapper: DEBUG